language: node_js
node_js: 
  - "8"
dist: jessie
sudo: false

cache: 
  directories: 
    - node_modules

addons: 
  chrome: stable

script: 
  - npm install
  - npm run lint
  - npm run test
  - npm run build